// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGV2RVBTCWjy_ChCK4Yp-KpirIcYnKh-o',
    appId: '1:625242198737:web:381c0ed2c90ab68d6debf0',
    messagingSenderId: '625242198737',
    projectId: 'malaz-project',
    authDomain: 'malaz-project.firebaseapp.com',
    storageBucket: 'malaz-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl2oIWkUmtICf2Jj-ZWB4v4lDLRsWwB4o',
    appId: '1:625242198737:android:74fe02aa2c6ab4376debf0',
    messagingSenderId: '625242198737',
    projectId: 'malaz-project',
    storageBucket: 'malaz-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM1zEEIRM2A3mGyvpixFW6z6_sWm3H7lc',
    appId: '1:625242198737:ios:35009c56260203c56debf0',
    messagingSenderId: '625242198737',
    projectId: 'malaz-project',
    storageBucket: 'malaz-project.firebasestorage.app',
    iosBundleId: 'com.example.malaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM1zEEIRM2A3mGyvpixFW6z6_sWm3H7lc',
    appId: '1:625242198737:ios:35009c56260203c56debf0',
    messagingSenderId: '625242198737',
    projectId: 'malaz-project',
    storageBucket: 'malaz-project.firebasestorage.app',
    iosBundleId: 'com.example.malaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGV2RVBTCWjy_ChCK4Yp-KpirIcYnKh-o',
    appId: '1:625242198737:web:46ea5aeeb56ebd4a6debf0',
    messagingSenderId: '625242198737',
    projectId: 'malaz-project',
    authDomain: 'malaz-project.firebaseapp.com',
    storageBucket: 'malaz-project.firebasestorage.app',
  );
}
