<?php

namespace Database\Seeders;

use App\Models\Property;
use Database\Factories\PropertyFactory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $base64Images = [];
        for ($i = 1; $i <= 5; $i++) {
            $path = database_path("seeders/images/properties/{$i}.png");
            $base64Images[$i] = base64_encode(file_get_contents($path));
        }

        $properties = [
            // [
            //     'title' => 'شقة في برجي التجارة العالميين - نيويورك',
            //     'price' => 1500000,
            //     'city' => 'نيويورك',
            //     'governorate' => 'نيويورك',
            //     'address' => 'مركز التجارة العالمي، مانهاتن',
            //     'description' => 'شقة فاخرة بإطلالة مباشرة على مدينة نيويورك من برجي التجارة العالميين.',
            //     'latitude' => '40.7127',
            //     'longitude' => '-74.0134',
            //     'type' => 'Residential Tower',
            //     'number_of_rooms' => 6,
            //     'number_of_baths' => 3,
            //     'number_of_bedrooms' => 4,
            //     'area' => 220,
            //     'rating' => 5,
            //     'number_of_reviews' => 50,
            //     'main_image' => $base64Images[1],
            //     'mime_type' => 'image/png',
            // 'owner_id' => rand(2,5),
            // 'status' => 'approved',
            // ],
            [
                'title' => 'شقة في برج خليفة - دبي',
                'price' => 2000000,
                'city' => 'دبي',
                'governorate' => 'دبي',
                'address' => 'برج خليفة، وسط مدينة دبي',
                'description' => 'شقة حديثة في أعلى برج بالعالم مع إطلالة بانورامية على دبي.',
                'latitude' => '25.1972',
                'longitude' => '55.2744',
                'type' => 'Residential Tower',
                'number_of_rooms' => 5,
                'number_of_baths' => 3,
                'number_of_bedrooms' => 3,
                'area' => 180,
                'rating' => 5,
                'number_of_reviews' => 70,
                'main_image' => $base64Images[2],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'فيلا على شاطئ ميامي',
                'price' => 1200000,
                'city' => 'ميامي',
                'governorate' => 'فلوريدا',
                'address' => 'شاطئ ميامي، فلوريدا',
                'description' => 'فيلا فاخرة مع مسبح خاص وإطلالة على المحيط الأطلسي.',
                'latitude' => '25.7906',
                'longitude' => '-80.1300',
                'type' => 'Villa',
                'number_of_rooms' => 8,
                'number_of_baths' => 4,
                'number_of_bedrooms' => 5,
                'area' => 350,
                'status' => 'approved',
                'rating' => 5,
                'number_of_reviews' => 40,
                'main_image' => $base64Images[3],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
            ],
            [
                'title' => 'مطعم في ساحة سان ماركو - البندقية',
                'price' => 500000,
                'city' => 'البندقية',
                'governorate' => 'فينيتو',
                'address' => 'ساحة سان ماركو، البندقية',
                'description' => 'مطعم إيطالي تقليدي في قلب البندقية، يقدم أطباق محلية شهيرة.',
                'latitude' => '45.4340',
                'longitude' => '12.3380',
                'type' => 'Restaurant',
                'number_of_rooms' => 3,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 0,
                'area' => 120,
                'rating' => 4,
                'number_of_reviews' => 25,
                'main_image' => $base64Images[4],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
            ],
            [
                'title' => 'مزرعة زيتون في ريف دمشق',
                'price' => 300000,
                'city' => 'ريف دمشق',
                'governorate' => 'دمشق',
                'address' => 'الغوطة الشرقية',
                'description' => 'مزرعة واسعة مزروعة بأشجار الزيتون مع بيت ريفي صغير.',
                'latitude' => '33.5138',
                'longitude' => '36.2765',
                'type' => 'Farm',
                'number_of_rooms' => 4,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 2,
                'area' => 500,
                'rating' => 4,
                'number_of_reviews' => 15,
                'main_image' => $base64Images[5],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',

            ],
            // [
            //     'title' => 'Apartment in Eiffel Tower Style',
            //     'price' => 1800000,
            //     'city' => 'Damascus',
            //     'governorate' => 'Damascus',
            //     'address' => 'Mazzeh Street',
            //     'description' => 'Luxury apartment styled like Paris Eiffel Tower, located in Damascus.',
            //     'latitude' => '33.5138',
            //     'longitude' => '36.2765',
            //     'type' => 'Residential Tower',
            //     'number_of_rooms' => 4,
            //     'number_of_baths' => 2,
            //     'number_of_bedrooms' => 2,
            //     'area' => 150,
            //     'rating' => 5,
            //     'number_of_reviews' => 60,
            //     'main_image' => $base64Images[6],
            //     'mime_type' => 'image/png',
            //     'owner_id' => rand(2, 5),
            // ],
            // [
            //     'title' => 'Grape Farm in Tuscany Style',
            //     'price' => 400000,
            //     'city' => 'Homs',
            //     'governorate' => 'Homs',
            //     'address' => 'Al Waer District',
            //     'description' => 'Wide farm planted with grapes, inspired by Tuscany, located in Homs.',
            //     'latitude' => '34.7300',
            //     'longitude' => '36.7200',
            //     'type' => 'Farm',
            //     'number_of_rooms' => 6,
            //     'number_of_baths' => 2,
            //     'number_of_bedrooms' => 3,
            //     'area' => 600,
            //     'rating' => 4,
            //     'number_of_reviews' => 20,
            //     'main_image' => $base64Images[7],
            //     'mime_type' => 'image/png',
            //     'owner_id' => rand(2, 5),
            // ],
            // [
            //     'title' => 'Villa in Maldives Style',
            //     'price' => 2500000,
            //     'city' => 'Latakia',
            //     'governorate' => 'Latakia',
            //     'address' => 'Corniche Al Bahar',
            //     'description' => 'Luxury villa over water, inspired by Maldives, located in Latakia.',
            //     'latitude' => '35.5167',
            //     'longitude' => '35.7833',
            //     'type' => 'Villa',
            //     'number_of_rooms' => 7,
            //     'number_of_baths' => 3,
            //     'number_of_bedrooms' => 4,
            //     'area' => 300,
            //     'rating' => 5,
            //     'number_of_reviews' => 35,
            //     'main_image' => $base64Images[8],
            //     'mime_type' => 'image/png',
            //     'owner_id' => rand(2, 5),
            // ],
            // [
            //     'title' => 'Restaurant in Times Square Style',
            //     'price' => 800000,
            //     'city' => 'Aleppo',
            //     'governorate' => 'Aleppo',
            //     'address' => 'Aziziyah Street',
            //     'description' => 'International restaurant inspired by Times Square, located in Aleppo.',
            //     'latitude' => '36.2021',
            //     'longitude' => '37.1343',
            //     'type' => 'Restaurant',
            //     'number_of_rooms' => 5,
            //     'number_of_baths' => 2,
            //     'number_of_bedrooms' => 0,
            //     'area' => 200,
            //     'rating' => 4,
            //     'number_of_reviews' => 45,
            //     'main_image' => $base64Images[9],
            //     'mime_type' => 'image/png',
            //     'owner_id' => rand(2, 5),
            // ],
            // [
            //     'title' => 'Travel Rest Stop on Silk Road Style',
            //     'price' => 150000,
            //     'city' => 'Deir ez-Zor',
            //     'governorate' => 'Deir ez-Zor',
            //     'address' => 'Mayadin Road',
            //     'description' => 'Traditional rest stop inspired by Silk Road, located in Deir ez-Zor.',
            //     'latitude' => '35.3333',
            //     'longitude' => '40.1500',
            //     'type' => 'Travel Rest Stop',
            //     'number_of_rooms' => 10,
            //     'number_of_baths' => 4,
            //     'number_of_bedrooms' => 6,
            //     'area' => 400,
            //     'rating' => 3,
            //     'number_of_reviews' => 12,
            //     'main_image' => $base64Images[10],
            //     'mime_type' => 'image/png',
            //     'owner_id' => rand(2, 5),
            // ],
            // [
            //     'title' => 'Apartment in CN Tower Style',
            //     'price' => 1300000,
            //     'city' => 'Tartus',
            //     'governorate' => 'Tartus',
            //     'address' => 'Corniche Street',
            //     'description' => 'Modern apartment inspired by Toronto CN Tower, located in Tartus.',
            //     'latitude' => '34.8833',
            //     'longitude' => '35.8833',
            //     'type' => 'Residential Tower',
            //     'number_of_rooms' => 4,
            //     'number_of_baths' => 2,
            //     'number_of_bedrooms' => 2,
            //     'area' => 160,
            //     'rating' => 5,
            //     'number_of_reviews' => 30,
            //     'main_image' => $base64Images[11],
            //     'mime_type' => 'image/png',
            //     'owner_id' => rand(2, 5),
            // ],
            // [
            //     'title' => 'Country Estate in Salzburg Style',
            //     'price' => 900000,
            //     'city' => 'Sweida',
            //     'governorate' => 'Sweida',
            //     'address' => 'Rural Sweida',
            //     'description' => 'Wide country estate inspired by Austria Salzburg, located in Sweida.',
            //     'latitude' => '32.7086',
            //     'longitude' => '36.5667',
            //     'type' => 'Country Estate',
            //     'number_of_rooms' => 12,
            //     'number_of_baths' => 5,
            //     'number_of_bedrooms' => 8,
            //     'area' => 800,
            //     'rating' => 5,
            //     'number_of_reviews' => 22,
            //     'main_image' => $base64Images[12],
            //     'mime_type' => 'image/png',
            //     'owner_id' => rand(2, 5),
            // ],
            // [
            //     'title' => 'Apartment in Shard Tower Style',
            //     'price' => 1700000,
            //     'city' => 'Raqqa',
            //     'governorate' => 'Raqqa',
            //     'address' => 'Al Thakafa Street',
            //     'description' => 'Modern apartment inspired by London Shard Tower, located in Raqqa.',
            //     'latitude' => '35.9500',
            //     'longitude' => '39.0167',
            //     'type' => 'Residential Tower',
            //     'number_of_rooms' => 5,
            //     'number_of_baths' => 2,
            //     'number_of_bedrooms' => 3,
            //     'area' => 190,
            //     'rating' => 5,
            //     'number_of_reviews' => 55,
            //     'main_image' => $base64Images[13],
            //     'mime_type' => 'image/png',
            //     'owner_id' => rand(2, 5),
            // ],
            // [
            //     'title' => 'Coffee Farm in Brazil Style',
            //     'price' => 350000,
            //     'city' => 'Idlib',
            //     'governorate' => 'Idlib',
            //     'address' => 'Countryside Idlib',
            //     'description' => 'Wide farm planted with coffee, inspired by Brazil, located in Idlib.',
            //     'latitude' => '35.9333',
            //     'longitude' => '36.6333',
            //     'type' => 'Farm',
            //     'number_of_rooms' => 5,
            //     'number_of_baths' => 2,
            //     'number_of_bedrooms' => 3,
            //     'area' => 700,
            //     'rating' => 4,
            //     'number_of_reviews' => 18,
            //     'main_image' => $base64Images[14],
            //     'mime_type' => 'image/png',
            //     'owner_id' => rand(2, 5),
            // ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }

    }
}
