<?php

namespace Database\Seeders;

use App\Models\Property;
use Database\Factories\PropertyFactory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cnt = 0;
        $use = 0;
        $base64Images = [];
        $secImagespath = [];
        for ($i = 1; $i <= 25; $i++) {
            $ind = $i;
            $path = database_path("seeders/images/properties/main{$i}.png");
            if (file_exists($path)) {
                $base64Images[$i - 1] = base64_encode(file_get_contents($path));
                $use = 1 + $use;
            } else {
                $ind = rand(1, $use);
                $path = database_path("seeders/images/properties/main{$ind}.png");
                $base64Images[$i - 1] = base64_encode(file_get_contents($path));
            }
            $ind = ($ind - 1) * 3;
            $secImagespath[] = [$ind + 1, $ind + 2, $ind + 3];
            $cnt = 1 + $cnt;
        }

        $properties = [
            [
                'title' => 'شقة حديثة في أبو رمانة',
                'price' => rand(1, 100) * 100,
                'city' => 'Damascus',
                'governorate' => 'Damascus Governorate',
                'address' => 'Abu Rummaneh, near Al-Shaalan',
                'description' => 'شقة واسعة في قلب دمشق مع إطلالة جميلة على المدينة.',
                'latitude' => '33.5141',
                'longitude' => '36.2765',
                'type' => 'Apartment',
                'number_of_rooms' => 4,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 3,
                'area' => 150,
                'rating' => 4,
                'number_of_reviews' => 25,
                'main_image' => $base64Images[0],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Luxury Villa in Al-Hamra',
                'price' => rand(1, 100) * 100,
                'city' => 'Aleppo',
                'governorate' => 'Aleppo Governorate',
                'address' => 'Al-Hamra district, western Aleppo',
                'description' => 'Spacious villa with private garden and modern design.',
                'latitude' => '36.2154',
                'longitude' => '37.1596',
                'type' => 'Villa',
                'number_of_rooms' => 7,
                'number_of_baths' => 4,
                'number_of_bedrooms' => 5,
                'area' => 400,
                'rating' => 5,
                'number_of_reviews' => 40,
                'main_image' => $base64Images[1],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'بيت ريفي في بلودان',
                'price' => rand(1, 100) * 100,
                'city' => 'Bloudan',
                'governorate' => 'Rif Dimashq Governorate',
                'address' => 'Bloudan hills, near the pine forest',
                'description' => 'منزل ريفي مريح مع إطلالة جبلية رائعة، مثالي للعطلات الصيفية.',
                'latitude' => '33.7333',
                'longitude' => '36.0833',
                'type' => 'Country House',
                'number_of_rooms' => 5,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 3,
                'area' => 200,
                'rating' => 4,
                'number_of_reviews' => 18,
                'main_image' => $base64Images[2],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Farm in Al-Ghab Plain',
                'price' => rand(1, 100) * 100,
                'city' => 'Al-Ghab',
                'governorate' => 'Hama Governorate',
                'address' => 'Al-Ghab plain, near Al-Suqaylabiyah',
                'description' => 'Agricultural farm with wide land suitable for crops and livestock.',
                'latitude' => '35.3667',
                'longitude' => '36.4000',
                'type' => 'Farm',
                'number_of_rooms' => 3,
                'number_of_baths' => 1,
                'number_of_bedrooms' => 2,
                'area' => 1000,
                'rating' => 3,
                'number_of_reviews' => 10,
                'main_image' => $base64Images[3],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'منزل على الكورنيش في طرطوس',
                'price' => rand(1, 100) * 100,
                'city' => 'Tartus',
                'governorate' => 'Tartus Governorate',
                'address' => 'Corniche, Tartus seaside',
                'description' => 'منزل جميل بإطلالة مباشرة على البحر مع تصميم عصري.',
                'latitude' => '34.8833',
                'longitude' => '35.8833',
                'type' => 'House',
                'number_of_rooms' => 6,
                'number_of_baths' => 3,
                'number_of_bedrooms' => 4,
                'area' => 250,
                'rating' => 5,
                'number_of_reviews' => 32,
                'main_image' => $base64Images[4],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'شقة للإيجار في المزة',
                'price' => rand(1, 100) * 100,
                'city' => 'Damascus',
                'governorate' => 'Damascus Governorate',
                'address' => 'Mazzeh, near Damascus University',
                'description' => 'شقة مريحة قريبة من الجامعة والخدمات الأساسية.',
                'latitude' => '33.5074',
                'longitude' => '36.2769',
                'type' => 'Apartment',
                'number_of_rooms' => 3,
                'number_of_baths' => 1,
                'number_of_bedrooms' => 2,
                'area' => 120,
                'rating' => 4,
                'number_of_reviews' => 12,
                'main_image' => $base64Images[5],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Modern House in Latakia',
                'price' => rand(1, 100) * 100,
                'city' => 'Latakia',
                'governorate' => 'Latakia Governorate',
                'address' => 'Al-Corniche Al-Janoubi, Latakia',
                'description' => 'A modern house with sea view and spacious rooms.',
                'latitude' => '35.5167',
                'longitude' => '35.7833',
                'type' => 'House',
                'number_of_rooms' => 5,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 3,
                'area' => 200,
                'rating' => 5,
                'number_of_reviews' => 20,
                'main_image' => $base64Images[6],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'فيلا فاخرة في يعفور',
                'price' => rand(1, 100) * 100,
                'city' => 'Yaafour',
                'governorate' => 'Rif Dimashq Governorate',
                'address' => 'Yaafour luxury villas area',
                'description' => 'فيلا واسعة مع مسبح وحديقة خاصة في منطقة يعفور الراقية.',
                'latitude' => '33.5667',
                'longitude' => '36.0833',
                'type' => 'Villa',
                'number_of_rooms' => 8,
                'number_of_baths' => 5,
                'number_of_bedrooms' => 6,
                'area' => 500,
                'rating' => 5,
                'number_of_reviews' => 45,
                'main_image' => $base64Images[7],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Country House in Kassab',
                'price' => rand(1, 100) * 100,
                'city' => 'Kassab',
                'governorate' => 'Latakia Governorate',
                'address' => 'Kassab mountains, near pine forest',
                'description' => 'Cozy country house surrounded by nature, ideal for family vacations.',
                'latitude' => '35.9333',
                'longitude' => '35.9833',
                'type' => 'Country House',
                'number_of_rooms' => 4,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 3,
                'area' => 180,
                'rating' => 4,
                'number_of_reviews' => 15,
                'main_image' => $base64Images[8],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'مزرعة صغيرة في ريف حمص',
                'price' => rand(1, 100) * 100,
                'city' => 'Homs',
                'governorate' => 'Homs Governorate',
                'address' => 'Countryside of Homs, near Al-Rastan',
                'description' => 'مزرعة صغيرة مناسبة لتربية الحيوانات وزراعة الخضار.',
                'latitude' => '34.7333',
                'longitude' => '36.7167',
                'type' => 'Farm',
                'number_of_rooms' => 2,
                'number_of_baths' => 1,
                'number_of_bedrooms' => 1,
                'area' => 800,
                'rating' => 3,
                'number_of_reviews' => 8,
                'main_image' => $base64Images[9],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'شقة صغيرة في باب توما',
                'price' => rand(1, 100) * 100,
                'city' => 'Damascus',
                'governorate' => 'Damascus Governorate',
                'address' => 'Bab Touma, Old Damascus',
                'description' => 'شقة تقليدية في قلب دمشق القديمة، مناسبة للسكن الفردي.',
                'latitude' => '33.5145',
                'longitude' => '36.3069',
                'type' => 'Apartment',
                'number_of_rooms' => 2,
                'number_of_baths' => 1,
                'number_of_bedrooms' => 1,
                'area' => 70,
                'rating' => 3,
                'number_of_reviews' => 6,
                'main_image' => $base64Images[10],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Seaside Apartment in Jableh',
                'price' => rand(1, 100) * 100,
                'city' => 'Jableh',
                'governorate' => 'Latakia Governorate',
                'address' => 'Jableh Corniche, near the port',
                'description' => 'Bright apartment with sea view, perfect for summer rentals.',
                'latitude' => '35.3500',
                'longitude' => '35.9167',
                'type' => 'Apartment',
                'number_of_rooms' => 3,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 2,
                'area' => 110,
                'rating' => 4,
                'number_of_reviews' => 14,
                'main_image' => $base64Images[11],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'منزل عائلي في حلب الجديدة',
                'price' => rand(1, 100) * 100,
                'city' => 'Aleppo',
                'governorate' => 'Aleppo Governorate',
                'address' => 'New Aleppo district',
                'description' => 'منزل واسع مناسب للعائلات الكبيرة مع حديقة صغيرة.',
                'latitude' => '36.2167',
                'longitude' => '37.1667',
                'type' => 'House',
                'number_of_rooms' => 6,
                'number_of_baths' => 3,
                'number_of_bedrooms' => 4,
                'area' => 220,
                'rating' => 4,
                'number_of_reviews' => 22,
                'main_image' => $base64Images[12],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Villa in Safita Hills',
                'price' => rand(1, 100) * 100,
                'city' => 'Safita',
                'governorate' => 'Tartus Governorate',
                'address' => 'Safita hillside, overlooking the valley',
                'description' => 'Elegant villa with panoramic views and private pool.',
                'latitude' => '34.8167',
                'longitude' => '36.1333',
                'type' => 'Villa',
                'number_of_rooms' => 7,
                'number_of_baths' => 4,
                'number_of_bedrooms' => 5,
                'area' => 350,
                'rating' => 5,
                'number_of_reviews' => 28,
                'main_image' => $base64Images[13],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'بيت ريفي في سلمية',
                'price' => rand(1, 100) * 100,
                'city' => 'Salamiyah',
                'governorate' => 'Hama Governorate',
                'address' => 'Countryside of Salamiyah',
                'description' => 'بيت ريفي بسيط مع مساحة أرض واسعة للزراعة.',
                'latitude' => '35.0167',
                'longitude' => '37.0500',
                'type' => 'Country House',
                'number_of_rooms' => 4,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 3,
                'area' => 160,
                'rating' => 3,
                'number_of_reviews' => 9,
                'main_image' => $base64Images[14],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Квартира в центре Дамаска',
                'price' => rand(1, 100) * 100,
                'city' => 'Damascus',
                'governorate' => 'Damascus Governorate',
                'address' => 'Central Damascus, near Al-Hamidiya',
                'description' => 'Уютная квартира рядом с рынком и историческими местами.',
                'latitude' => '33.5138',
                'longitude' => '36.2765',
                'type' => 'Apartment',
                'number_of_rooms' => 3,
                'number_of_baths' => 1,
                'number_of_bedrooms' => 2,
                'area' => 95,
                'rating' => 4,
                'number_of_reviews' => 11,
                'main_image' => $base64Images[15],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Modern House in Aleppo',
                'price' => rand(1, 100) * 100,
                'city' => 'Aleppo',
                'governorate' => 'Aleppo Governorate',
                'address' => 'New Aleppo district',
                'description' => 'Geniş ve modern ev, aileler için uygun.',
                'latitude' => '36.2167',
                'longitude' => '37.1667',
                'type' => 'House',
                'number_of_rooms' => 5,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 3,
                'area' => 180,
                'rating' => 4,
                'number_of_reviews' => 19,
                'main_image' => $base64Images[16],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Вилла у моря в Латакии',
                'price' => rand(1, 100) * 100,
                'city' => 'Latakia',
                'governorate' => 'Latakia Governorate',
                'address' => 'Latakia seaside, near Corniche',
                'description' => 'Просторная вилла с видом на море и большим садом.',
                'latitude' => '35.5167',
                'longitude' => '35.7833',
                'type' => 'Villa',
                'number_of_rooms' => 7,
                'number_of_baths' => 4,
                'number_of_bedrooms' => 5,
                'area' => 350,
                'rating' => 5,
                'number_of_reviews' => 30,
                'main_image' => $base64Images[17],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Maison de campagne à Bloudan',
                'price' => rand(1, 100) * 100,
                'city' => 'Bloudan',
                'governorate' => 'Rif Dimashq Governorate',
                'address' => 'Bloudan hills, near pine forest',
                'description' => 'Charmante maison de campagne avec vue sur les montagnes.',
                'latitude' => '33.7333',
                'longitude' => '36.0833',
                'type' => 'Country House',
                'number_of_rooms' => 4,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 3,
                'area' => 170,
                'rating' => 4,
                'number_of_reviews' => 14,
                'main_image' => $base64Images[18],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Deniz kenarında daire - Tartus',
                'price' => rand(1, 100) * 100,
                'city' => 'Tartus',
                'governorate' => 'Tartus Governorate',
                'address' => 'Tartus Corniche',
                'description' => 'Deniz manzaralı modern daire, tatil için mükemmel.',
                'latitude' => '34.8833',
                'longitude' => '35.8833',
                'type' => 'Apartment',
                'number_of_rooms' => 3,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 2,
                'area' => 130,
                'rating' => 5,
                'number_of_reviews' => 21,
                'main_image' => $base64Images[19],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Апартаменты в Хомсе',
                'price' => rand(1, 100) * 100,
                'city' => 'Homs',
                'governorate' => 'Homs Governorate',
                'address' => 'Downtown Homs, near Clock Tower',
                'description' => 'Светлая квартира в центре города, рядом с магазинами и кафе.',
                'latitude' => '34.7333',
                'longitude' => '36.7167',
                'type' => 'Apartment',
                'number_of_rooms' => 3,
                'number_of_baths' => 1,
                'number_of_bedrooms' => 2,
                'area' => 100,
                'rating' => 4,
                'number_of_reviews' => 13,
                'main_image' => $base64Images[20],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Maison moderne à Tartus',
                'price' => rand(1, 100) * 100,
                'city' => 'Tartus',
                'governorate' => 'Tartus Governorate',
                'address' => 'Tartus Corniche, near Marina',
                'description' => 'Maison moderne avec vue sur la mer et grand balcon.',
                'latitude' => '34.8833',
                'longitude' => '35.8833',
                'type' => 'House',
                'number_of_rooms' => 5,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 3,
                'area' => 190,
                'rating' => 5,
                'number_of_reviews' => 17,
                'main_image' => $base64Images[21],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Villa à Safita',
                'price' => rand(1, 100) * 100,
                'city' => 'Safita',
                'governorate' => 'Tartus Governorate',
                'address' => 'Safita hillside, overlooking valley',
                'description' => 'Grande villa élégante avec piscine privée et jardin.',
                'latitude' => '34.8167',
                'longitude' => '36.1333',
                'type' => 'Villa',
                'number_of_rooms' => 8,
                'number_of_baths' => 4,
                'number_of_bedrooms' => 5,
                'area' => 420,
                'rating' => 5,
                'number_of_reviews' => 29,
                'main_image' => $base64Images[22],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Deniz manzaralı villa - Latakia',
                'price' => rand(1, 100) * 100,
                'city' => 'Latakia',
                'governorate' => 'Latakia Governorate',
                'address' => 'Latakia seaside, near Corniche',
                'description' => 'Deniz manzaralı geniş villa, tatil için ideal.',
                'latitude' => '35.5167',
                'longitude' => '35.7833',
                'type' => 'Villa',
                'number_of_rooms' => 7,
                'number_of_baths' => 3,
                'number_of_bedrooms' => 4,
                'area' => 360,
                'rating' => 5,
                'number_of_reviews' => 26,
                'main_image' => $base64Images[23],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
            [
                'title' => 'Коттедж в Сувейде',
                'price' => rand(1, 100) * 100,
                'city' => 'As-Suwayda',
                'governorate' => 'As-Suwayda Governorate',
                'address' => 'Countryside of As-Suwayda',
                'description' => 'Уютный коттедж с садом и видом на горы.',
                'latitude' => '32.7086',
                'longitude' => '36.5667',
                'type' => 'Country House',
                'number_of_rooms' => 4,
                'number_of_baths' => 2,
                'number_of_bedrooms' => 3,
                'area' => 180,
                'rating' => 4,
                'number_of_reviews' => 12,
                'main_image' => $base64Images[24],
                'mime_type' => 'image/png',
                'owner_id' => rand(2, 5),
                'status' => 'approved',
            ],
        ];

        $factor = Property::factory()->count(50)->raw();

        foreach ($factor as &$f) {
            $ind = rand(1, $use);
            $path = database_path("seeders/images/properties/main{$ind}.png");
            $f['main_image'] = base64_encode(file_get_contents($path));
            $f['mime_type'] = 'image/png';
            $ind = ($ind - 1) * 3;
            $secImagespath[] = [$ind + 1, $ind + 2, $ind + 3];
            $cnt = 1 + $cnt;

        }

        unset($f);

        $properties = array_merge($properties, $factor);

        $properties = array_reverse($properties);

        foreach ($properties as $propertyData) {
            $cnt = $cnt - 1;
            $property = Property::create($propertyData);
            foreach ($secImagespath[$cnt] as $ind) {
                $path = database_path("seeders/images/properties/sec{$ind}.png");
                if (file_exists($path)) {
                    $imageData = base64_encode(file_get_contents($path));
                    $property->images()->create([
                        'image' => $imageData,
                        'mime_type' => 'image/png',
                    ]);
                }
            }
        }

    }
}
